(() => {
  const bank = Array.isArray(window.TERM_BANK) ? window.TERM_BANK : [];
  const level=window.IPAS_LEVEL||'intermediate';
  const statsKey='ipasPlayStats:'+level;
  let generation=0;
  const later=(fn,ms)=>{const g=generation;setTimeout(()=>{if(g===generation)fn()},ms)};
  let reviewAction=null;
  const continueBtn=document.createElement('button');continueBtn.type='button';continueBtn.id='continueReview';continueBtn.textContent='看懂了，繼續冒險 →';continueBtn.hidden=true;document.getElementById('feedback').after(continueBtn);
  continueBtn.onclick=()=>{const action=reviewAction;reviewAction=null;continueBtn.hidden=true;action?.()};
  function afterReview(fn,delay=1000){if(document.getElementById('learnMode').checked){reviewAction=fn;continueBtn.hidden=false}else later(fn,delay)}
  function clearReview(){reviewAction=null;continueBtn.hidden=true}
  const zhMap = window.TERM_ZH || {};
  const $ = (id) => document.getElementById(id);
  const els = {
    category:$('categorySelect'),score:$('score'),combo:$('combo'),best:$('bestScore'),total:$('totalAnswered'),wrong:$('wrongCount'),correct:$('correctCount'),feedback:$('feedback'),
    truckModeBtn:$('truckModeBtn'),memoryModeBtn:$('memoryModeBtn'),cannonModeBtn:$('cannonModeBtn'),newRoundBtn:$('newRoundBtn'),
    truckGame:$('truckGame'),memoryGame:$('memoryGame'),cannonGame:$('cannonGame'),road:$('road'),truck:$('truck'),truckTerm:$('truckTerm'),cargo:$('cargoOptions'),speed:$('speedLevel'),timerBar:$('timerBar'),
    truckPauseBtn:$('truckPauseBtn'),truckNextBtn:$('truckNextBtn'),memoryBoard:$('memoryBoard'),memoryProgress:$('memoryProgress'),
    cannonClue:$('cannonClue'),cannonArena:$('cannonArena'),brickCeiling:$('brickCeiling'),cannon:$('cannon'),bullet:$('bullet'),dropLevel:$('dropLevel'),cannonLeft:$('cannonLeft'),cannonRight:$('cannonRight'),cannonFire:$('cannonFire')
  };
  const state={mode:'truck',score:0,combo:0,correct:0,truckIndex:0,truckQueue:[],truckTimer:null,truckStartedAt:0,truckDuration:12000,truckRemaining:12000,truckPaused:false,truckReview:false,memoryPairs:[],memoryOpen:[],memoryMatched:new Set(),memoryLock:false,cannonItems:[],cannonTarget:null,cannonCol:2,cannonDrop:0,cannonLocked:false,stats:loadStats()};

  function loadStats(){try{const raw=JSON.parse((localStorage.getItem(statsKey)||(level==='intermediate'?localStorage.getItem('ipasPlayStats'):null))||'{}');return{bestScore:Number(raw.bestScore)||0,totalAnswered:Number(raw.totalAnswered)||0,wrongIds:Array.isArray(raw.wrongIds)?raw.wrongIds:[]};}catch{return{bestScore:0,totalAnswered:0,wrongIds:[]};}}
  function saveStats(){localStorage.setItem(statsKey,JSON.stringify(state.stats));}
  function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function pool(){const c=els.category.value;return c==='REVIEW'?bank.filter(x=>state.stats.wrongIds.includes(x.id)):c==='ALL'?bank:bank.filter(x=>x.category===c);}
  function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
  function zh(item){return item.zh || window.IPAS_TRANSLATIONS?.[item.term] || zhMap[item.term] || item.term;}
  function initCategories(){const cats=[...new Set(bank.map(x=>x.category))];els.category.innerHTML='<option value="ALL">全範圍混合（'+bank.length+'）</option>';cats.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=`${c}（${bank.filter(x=>x.category===c).length}）`;els.category.appendChild(o);});els.category.add(new Option('📖 錯題再練','REVIEW'));if(new URLSearchParams(location.search).has('review'))els.category.value='REVIEW';}
  function updateHud(){els.score.textContent=state.score;els.combo.textContent=state.combo;els.best.textContent=state.stats.bestScore;els.total.textContent=state.stats.totalAnswered;els.wrong.textContent=state.stats.wrongIds.length;els.correct.textContent=state.correct;}
  function feedback(title,msg,type=''){els.feedback.className=`feedback card ${type}`.trim();els.feedback.innerHTML=`<strong>${esc(title)}</strong><p>${esc(msg)}</p>`;}
  function detailedFeedback(title,item,type=''){els.feedback.className=`feedback card ${type}`.trim();els.feedback.innerHTML=`<strong>${esc(title)}</strong><div class="answer-detail"><p><b>英文名詞：</b>${esc(item.term)}</p><p><b>中文譯名：</b>${esc(zh(item))}</p><p><b>核心定義：</b>${esc(item.definition)}</p><p><b>觀念辨識：</b>${esc(item.note || '記住它的用途、與相近名詞的差異，以及常見應用情境。')}</p><p><b>範圍：</b>${esc(item.scope||'延伸練習')} · ${esc(item.source||item.category)}</p><p>想一想：你能不看答案，舉出一個適用的情境嗎？</p></div>`;}
  function addWrong(id){if(!state.stats.wrongIds.includes(id))state.stats.wrongIds.unshift(id);}
  function markCorrect(item,points){window.gameSound?.correct();window.Community?.answer(level,item.id,item.id);state.combo++;state.correct++;state.score+=points+Math.min(state.combo,8)*3;state.stats.wrongIds=state.stats.wrongIds.filter(id=>id!==item.id);if(state.score>state.stats.bestScore)state.stats.bestScore=state.score;saveStats();updateHud();}
  function markWrong(item,penalty=5){window.gameSound?.wrong();state.combo=0;state.score=Math.max(0,state.score-penalty);state.stats.totalAnswered++;addWrong(item.id);saveStats();updateHud();}

  function stopTruck(){if(state.truckTimer){cancelAnimationFrame(state.truckTimer);state.truckTimer=null;}}
  function setMode(mode){generation++;clearReview();stopTruck();state.mode=mode;state.score=0;state.combo=0;state.correct=0;['truck','memory','cannon'].forEach(m=>{els[m+'ModeBtn']?.classList.toggle('active',mode===m);els[m+'Game']?.classList.toggle('hidden',mode!==m);});if(mode==='truck')startTruckGame();if(mode==='memory')startMemoryGame();if(mode==='cannon')startCannonGame();updateHud();}

  function startTruckGame(){generation++;clearReview();stopTruck();state.truckPaused=true;state.truckReview=true;els.truckNextBtn.classList.add('hidden');state.score=0;state.combo=0;state.correct=0;updateHud();if(!pool().length){els.cargo.replaceChildren();feedback('🎉 目前沒有錯題','可以切回全範圍混合繼續練習。');return;}stopTruck();state.truckQueue=shuffle(pool()).slice(0,Math.min(20,pool().length));state.truckIndex=0;state.truckDuration=12000;state.truckRemaining=12000;state.truckPaused=false;state.truckReview=false;state.combo=0;state.correct=0;els.truckPauseBtn.textContent='⏸ 暫停';els.truckNextBtn.classList.add('hidden');feedback('🚚 慢速車隊出發！','學習模式不限時；取消勾選可在下一題開始計時挑戰。每題先回想，再看詳解。');nextTruck();}
  function nextTruck(){stopTruck();if(state.mode!=='truck')return;if(state.truckIndex>=state.truckQueue.length){state.truckPaused=true;state.truckReview=true;els.truckNextBtn.classList.add('hidden');els.cargo.querySelectorAll('button').forEach(b=>b.disabled=true);feedback('🏁 車隊完成！',`本局答對 ${state.correct} 題，得分 ${state.score}。`,'good');return;}const item=state.truckQueue[state.truckIndex++];state.currentTruck=item;state.truckReview=false;state.truckPaused=false;els.truckPauseBtn.textContent='⏸ 暫停';els.truckNextBtn.classList.add('hidden');els.truckTerm.textContent=item.term;els.truck.className='truck';renderCargo(item);const level=Math.min(10,1+Math.floor(state.correct/4));els.speed.textContent=level;state.truckDuration=Math.max(3800,12000-(level-1)*900);state.truckRemaining=state.truckDuration;state.truckStartedAt=performance.now();animateTruck();}
  function animateTruck(){if(state.truckPaused||state.truckReview)return;if(document.getElementById('learnMode').checked){els.truck.style.transform='translateX(25px)';els.timerBar.style.transform='scaleX(1)';return;}const now=performance.now(),elapsed=now-state.truckStartedAt,p=Math.min(1,1-state.truckRemaining/state.truckDuration+elapsed/state.truckDuration);const roadW=els.road.clientWidth,truckW=els.truck.offsetWidth||260,start=-truckW,end=roadW+30;els.truck.style.transform=(document.body.classList.contains('reduce')||matchMedia('(prefers-reduced-motion: reduce)').matches)?'translateX(25px)':`translateX(${start+(end-start)*p}px)`;els.timerBar.style.transform=`scaleX(${1-p})`;if(p>=1){timeoutTruck();return;}state.truckTimer=requestAnimationFrame(animateTruck);}
  function toggleTruckPause(){if(state.mode!=='truck'||state.truckReview)return;if(state.truckPaused){state.truckPaused=false;state.truckStartedAt=performance.now();els.truckPauseBtn.textContent='⏸ 暫停';feedback('▶ 繼續行駛','從剛剛停下的位置繼續。');animateTruck();}else{const elapsed=performance.now()-state.truckStartedAt;state.truckRemaining=Math.max(0,state.truckRemaining-elapsed);state.truckPaused=true;stopTruck();els.truckPauseBtn.textContent='▶ 繼續';feedback('⏸ 已暫停','慢慢看題目與四個答案，想好再繼續。');}}
  function enterTruckReview(item,title,type){state.truckReview=true;state.truckPaused=true;stopTruck();els.truckPauseBtn.textContent='⏸ 已停車';els.truckNextBtn.classList.remove('hidden');detailedFeedback(title,item,type);}
  function timeoutTruck(){stopTruck();const item=state.currentTruck;markWrong(item);els.truck.classList.add('wrong');enterTruckReview(item,'💨 車跑掉了，先看懂這題','bad');}
  function renderCargo(correct){const others=shuffle(bank.filter(x=>x.id!==correct.id)).slice(0,3),opts=shuffle([correct,...others]);els.cargo.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='cargo-btn';b.innerHTML=`<span>${esc(o.definition)}</span>`;b.addEventListener('click',()=>chooseCargo(b,o));els.cargo.appendChild(b);});}
  function chooseCargo(btn,choice){if(state.truckPaused||state.truckReview)return;stopTruck();const item=state.currentTruck;state.stats.totalAnswered++;els.cargo.querySelectorAll('button').forEach(b=>b.disabled=true);if(choice.id===item.id){btn.classList.add('good');els.truck.classList.add('correct');markCorrect(item,30);detailedFeedback(`📦 裝貨成功！Combo × ${state.combo}`,item,'good');if(document.getElementById('learnMode').checked)enterTruckReview(item,'📦 裝貨成功！看懂後繼續','good');else later(nextTruck,1600);}else{btn.classList.add('bad');addWrong(item.id);state.combo=0;state.score=Math.max(0,state.score-5);saveStats();updateHud();enterTruckReview(item,'❌ 裝錯貨，先把這題看懂','bad');}}

  function startMemoryGame(){generation++;clearReview();state.score=0;state.combo=0;state.correct=0;updateHud();stopTruck();state.memoryPairs=shuffle(pool()).slice(0,Math.min(6,pool().length));state.memoryOpen=[];state.memoryMatched=new Set();state.memoryLock=false;state.combo=0;state.correct=0;renderMemory();feedback(state.memoryPairs.length?'🃏 翻牌開始':'目前沒有錯題',`找出 ${state.memoryPairs.length} 組「英文名詞＋中文概念」。先回想，再翻牌。`);}
  function renderMemory(){const cards=[];state.memoryPairs.forEach(item=>{cards.push({key:item.id+'-t',id:item.id,text:item.term,type:'term'});cards.push({key:item.id+'-d',id:item.id,text:item.definition,type:'definition'});});els.memoryBoard.innerHTML='';shuffle(cards).forEach(c=>{const b=document.createElement('button');b.type='button';b.className='memory-tile';b.dataset.key=c.key;b.setAttribute('aria-label','未翻開的卡片 '+(els.memoryBoard.children.length+1));b.innerHTML=`<span class="memory-inner"><span class="memory-face memory-back">?</span><span class="memory-face memory-front">${esc(c.text)}</span></span>`;b.addEventListener('click',()=>flipMemory(b,c));els.memoryBoard.appendChild(b);});updateMemoryProgress();}
  function flipMemory(btn,card){if(state.memoryLock||btn.classList.contains('flipped')||btn.classList.contains('matched'))return;btn.classList.add('flipped');btn.setAttribute('aria-label',card.text);window.gameSound?.flip();state.memoryOpen.push({btn,card});if(state.memoryOpen.length<2)return;const[a,b]=state.memoryOpen;if(a.card.id===b.card.id&&a.card.type!==b.card.type){state.stats.totalAnswered++;const item=bank.find(x=>x.id===a.card.id);markCorrect(item,20);a.btn.classList.add('matched');b.btn.classList.add('matched');a.btn.disabled=true;b.btn.disabled=true;state.memoryMatched.add(a.card.id);state.memoryOpen=[];detailedFeedback(`✨ 配對成功！Combo × ${state.combo}`,item,'good');updateMemoryProgress();state.memoryLock=true;afterReview(()=>{state.memoryLock=false;if(state.memoryMatched.size===state.memoryPairs.length)feedback('🎉 全部清空！',`你完成 ${state.memoryPairs.length} 組，得分 ${state.score}。`,'good')},1200);}else{state.memoryLock=true;state.stats.totalAnswered++;const item=bank.find(x=>x.id===a.card.id);addWrong(item.id);state.combo=0;state.score=Math.max(0,state.score-3);saveStats();updateHud();detailedFeedback('再想一下 👀 先看第一張的觀念',item,'bad');afterReview(()=>{a.btn.classList.remove('flipped');b.btn.classList.remove('flipped');a.btn.setAttribute('aria-label','未翻開的卡片');b.btn.setAttribute('aria-label','未翻開的卡片');state.memoryOpen=[];state.memoryLock=false;},1000);}}
  function updateMemoryProgress(){els.memoryProgress.textContent=`${state.memoryMatched.size} / ${state.memoryPairs.length}`;}

  function startCannonGame(){generation++;clearReview();state.score=0;state.combo=0;state.correct=0;updateHud();state.combo=0;state.correct=0;state.cannonDrop=0;state.cannonLocked=false;state.cannonCol=2;const source=shuffle(pool());state.cannonItems=source.slice(0,Math.min(15,source.length)).map((item,i)=>({item,col:i%5,hard:false,destroyed:false}));els.dropLevel.textContent='0';renderBricks();positionCannon();nextCannonTarget();if(!source.length){feedback('目前沒有錯題','切回全範圍混合繼續練習。');return}feedback('💥 高射炮裝填完成','看中文專有名詞，左右移動炮口。只要對準正確答案那一欄，就能直接擊中該英文磚。');}
  function renderBricks(){els.brickCeiling.innerHTML='';state.cannonItems.forEach((entry,i)=>{const d=document.createElement('div');d.className='term-brick'+(entry.hard?' hard':'')+(entry.destroyed?' destroyed':'');d.dataset.index=i;d.textContent=entry.item.term;els.brickCeiling.appendChild(d);});els.brickCeiling.style.transform=`translateY(${state.cannonDrop*34}px)`;}
  function nextCannonTarget(){const alive=state.cannonItems.filter(x=>!x.destroyed);if(!alive.length){feedback('🏆 天花板清空！',`本局答對 ${state.correct} 題，得分 ${state.score}。`,'good');state.cannonTarget=null;return;}state.cannonTarget=shuffle(alive)[0];els.cannonClue.textContent=`中文名詞：${zh(state.cannonTarget.item)}`;}
  function positionCannon(){const pct=((state.cannonCol+.5)/5)*100;els.cannon.style.left=`${pct}%`;}
  function moveCannon(dir){if(state.mode!=='cannon'||state.cannonLocked)return;state.cannonCol=Math.max(0,Math.min(4,state.cannonCol+dir));positionCannon();}
  function fireCannon(){
    if(state.mode!=='cannon'||state.cannonLocked||!state.cannonTarget)return;
    const targetIndex=state.cannonItems.findIndex(x=>!x.destroyed&&x.item.id===state.cannonTarget.item.id);
    if(targetIndex<0)return;
    const targetEntry=state.cannonItems[targetIndex];
    let hitIndex;
    if(targetEntry.col===state.cannonCol){
      hitIndex=targetIndex;
    }else{
      const candidates=state.cannonItems.map((x,i)=>({x,i})).filter(o=>!o.x.destroyed&&o.x.col===state.cannonCol);
      if(!candidates.length){feedback('💨 這一欄沒有磚','換一欄再射。','bad');return;}
      hitIndex=candidates[candidates.length-1].i;
    }
    state.cannonLocked=true;
    animateBullet(hitIndex,()=>resolveCannonHit(hitIndex));
  }
  function animateBullet(index,done){const brick=els.brickCeiling.querySelector(`[data-index="${index}"]`);if(!brick){done();return;}const arenaRect=els.cannonArena.getBoundingClientRect(),brickRect=brick.getBoundingClientRect(),cannonRect=els.cannon.getBoundingClientRect();const startX=cannonRect.left+cannonRect.width/2-arenaRect.left,startY=cannonRect.top-arenaRect.top,targetY=brickRect.bottom-arenaRect.top;els.bullet.classList.remove('hidden');els.bullet.style.left=`${startX}px`;els.bullet.style.top=`${startY}px`;const duration=(document.body.classList.contains('reduce')||matchMedia('(prefers-reduced-motion: reduce)').matches)?0:280,start=performance.now(),g=generation;function step(now){if(g!==generation){els.bullet.classList.add('hidden');return;}const p=duration?Math.min(1,(now-start)/duration):1;els.bullet.style.top=`${startY+(targetY-startY)*p}px`;if(p<1)requestAnimationFrame(step);else{els.bullet.classList.add('hidden');done();}}requestAnimationFrame(step);}
  function resolveCannonHit(index){const entry=state.cannonItems[index],target=state.cannonTarget.item;state.stats.totalAnswered++;if(entry.item.id===target.id){entry.destroyed=true;markCorrect(target,35);detailedFeedback(`💥 命中！Combo × ${state.combo}`,target,'good');renderBricks();afterReview(()=>{nextCannonTarget();state.cannonLocked=false});return;}else{entry.hard=true;state.combo=0;state.score=Math.max(0,state.score-5);addWrong(target.id);state.cannonDrop++;els.dropLevel.textContent=state.cannonDrop;saveStats();updateHud();renderBricks();detailedFeedback('🧱 射錯！磚塊硬化',target,'bad');afterReview(()=>{if(isCannonGameOver()){feedback('💀 磚牆壓到危險線！',`遊戲結束。本局答對 ${state.correct} 題。`,'bad');state.cannonTarget=null}else nextCannonTarget();state.cannonLocked=false});}}
  function isCannonGameOver(){const ceilingBottom=12+Math.ceil(state.cannonItems.length/5)*61+state.cannonDrop*34;const dangerY=els.cannonArena.clientHeight-94;return ceilingBottom>=dangerY;}

  els.truckModeBtn.addEventListener('click',()=>setMode('truck'));els.memoryModeBtn.addEventListener('click',()=>setMode('memory'));els.cannonModeBtn.addEventListener('click',()=>setMode('cannon'));
  els.newRoundBtn.addEventListener('click',()=>{if(state.mode==='truck')startTruckGame();if(state.mode==='memory')startMemoryGame();if(state.mode==='cannon')startCannonGame();});
  els.category.addEventListener('change',()=>{if(state.mode==='truck')startTruckGame();if(state.mode==='memory')startMemoryGame();if(state.mode==='cannon')startCannonGame();});
  els.truckPauseBtn.addEventListener('click',toggleTruckPause);els.truckNextBtn.addEventListener('click',nextTruck);
  els.cannonLeft.addEventListener('click',()=>moveCannon(-1));els.cannonRight.addEventListener('click',()=>moveCannon(1));els.cannonFire.addEventListener('click',fireCannon);
  document.addEventListener('keydown',e=>{if(state.mode!=='cannon'||/INPUT|SELECT|BUTTON|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();moveCannon(-1);}if(e.key==='ArrowRight'){e.preventDefault();moveCannon(1);}if(e.code==='Space'){e.preventDefault();fireCannon();}});
  initCategories();updateHud();const requested=new URLSearchParams(location.search).get('game');setMode(['truck','memory','cannon'].includes(requested)?requested:'truck');
})();
