window.TERM_BANK = [
  {id:'ml01',category:'AI / 機器學習核心',term:'Supervised Learning',definition:'使用已標註資料學習輸入與輸出之間的映射關係。',note:'常見任務包括分類與迴歸。'},
  {id:'ml02',category:'AI / 機器學習核心',term:'Unsupervised Learning',definition:'使用未標註資料尋找潛在結構或群組。',note:'常見方法包括分群與降維。'},
  {id:'ml03',category:'AI / 機器學習核心',term:'Reinforcement Learning',definition:'代理人透過與環境互動並依獎勵訊號學習策略。',note:'重點概念是狀態、動作、獎勵與策略。'},
  {id:'ml04',category:'AI / 機器學習核心',term:'Transfer Learning',definition:'把已在其他任務學到的知識轉移到新任務。',note:'可降低新任務所需的資料量與訓練成本。'},
  {id:'ml05',category:'AI / 機器學習核心',term:'Fine-tuning',definition:'以特定任務資料繼續訓練既有預訓練模型。',note:'通常更新全部或部分模型參數。'},
  {id:'ml06',category:'AI / 機器學習核心',term:'Overfitting',definition:'模型過度貼合訓練資料，導致泛化到新資料時表現變差。',note:'可用正則化、資料增強或交叉驗證等方式改善。'},
  {id:'ml07',category:'AI / 機器學習核心',term:'Underfitting',definition:'模型過於簡單，連訓練資料中的重要模式都沒有學好。',note:'通常訓練與測試表現都偏差。'},
  {id:'ml08',category:'AI / 機器學習核心',term:'Regularization',definition:'透過限制模型複雜度以降低過度擬合風險。',note:'常見有 L1、L2 正則化。'},
  {id:'ml09',category:'AI / 機器學習核心',term:'Feature Engineering',definition:'將原始資料轉換、組合或建立更適合模型學習的特徵。',note:'包含編碼、縮放、衍生欄位等。'},
  {id:'ml10',category:'AI / 機器學習核心',term:'Feature Selection',definition:'從既有特徵中挑選對模型最有幫助的子集合。',note:'目的包括降維、減少雜訊與提升可解釋性。'},
  {id:'ml11',category:'AI / 機器學習核心',term:'PCA',definition:'以線性方式找出最大變異方向並投影到較低維空間。',note:'主成分彼此正交，常用於降維。'},
  {id:'ml12',category:'AI / 機器學習核心',term:'t-SNE',definition:'非線性降維方法，常用於將高維資料視覺化到 2D 或 3D。',note:'強調保留局部鄰近結構，不適合直接解讀全域距離。'},
  {id:'ml13',category:'AI / 機器學習核心',term:'Autoencoder',definition:'透過編碼器與解碼器學習資料的壓縮表示。',note:'可用於降維、去雜訊與異常偵測。'},
  {id:'ml14',category:'AI / 機器學習核心',term:'K-means',definition:'把資料分成 K 個群集，使樣本靠近各自群中心。',note:'需事先指定 K 值。'},
  {id:'ml15',category:'AI / 機器學習核心',term:'KNN',definition:'依鄰近樣本的標籤或數值進行預測的實例式學習方法。',note:'K 代表參考的鄰居數量。'},
  {id:'stat01',category:'統計與模型評估',term:'Accuracy',definition:'所有預測中，預測正確的比例。',note:'類別嚴重不平衡時可能產生誤導。'},
  {id:'stat02',category:'統計與模型評估',term:'Precision',definition:'被模型判為正類的樣本中，實際為正類的比例。',note:'關注誤報 False Positive。'},
  {id:'stat03',category:'統計與模型評估',term:'Recall',definition:'所有實際正類樣本中，被模型成功找出的比例。',note:'關注漏報 False Negative。'},
  {id:'stat04',category:'統計與模型評估',term:'F1-score',definition:'Precision 與 Recall 的調和平均。',note:'適合需要兼顧精確率與召回率時使用。'},
  {id:'stat05',category:'統計與模型評估',term:'Confusion Matrix',definition:'用 TP、TN、FP、FN 彙整分類模型預測結果的表格。',note:'是理解分類錯誤型態的基礎工具。'},
  {id:'stat06',category:'統計與模型評估',term:'ROC Curve',definition:'以不同閾值下的真陽性率與假陽性率繪製的曲線。',note:'常搭配 AUC 評估分類能力。'},
  {id:'stat07',category:'統計與模型評估',term:'AUC',definition:'ROC 曲線下的面積，用來衡量模型區分正負類的能力。',note:'數值越接近 1 通常代表區分能力越好。'},
  {id:'stat08',category:'統計與模型評估',term:'MAE',definition:'預測值與真實值之絕對誤差的平均。',note:'相較 MSE 對極端誤差較不敏感。'},
  {id:'stat09',category:'統計與模型評估',term:'MSE',definition:'預測誤差平方後的平均。',note:'大誤差會被平方而受到較高懲罰。'},
  {id:'stat10',category:'統計與模型評估',term:'RMSE',definition:'MSE 開平方後的指標，單位與原目標變數一致。',note:'常用於迴歸模型評估。'},
  {id:'stat11',category:'統計與模型評估',term:'Pearson Correlation',definition:'衡量兩個連續變數之間線性相關程度的統計量。',note:'值介於 -1 到 1。'},
  {id:'stat12',category:'統計與模型評估',term:'Chi-square Test',definition:'用於檢驗類別變數之間是否具有統計關聯。',note:'特徵選擇時可用來評估類別特徵與目標的關聯。'},
  {id:'stat13',category:'統計與模型評估',term:'Z-score',definition:'表示資料點距離平均值多少個標準差的標準化分數。',note:'常用於標準化與異常值判斷。'},
  {id:'stat14',category:'統計與模型評估',term:'KS Statistic',definition:'衡量兩個累積分布之最大差距的統計量。',note:'可用於比較基準資料與目前資料是否產生漂移。'},
  {id:'stat15',category:'統計與模型評估',term:'PSI',definition:'Population Stability Index，用於衡量兩個資料分布的穩定性差異。',note:'常見於資料漂移與模型監控。'},
  {id:'gen01',category:'生成式 AI / NLP',term:'LLM',definition:'以大量文字資料訓練、具備語言理解與生成能力的大型語言模型。',note:'Large Language Model。'},
  {id:'gen02',category:'生成式 AI / NLP',term:'Token',definition:'模型處理文字時使用的基本切分單位。',note:'可能是一個字、字的一部分或標點。'},
  {id:'gen03',category:'生成式 AI / NLP',term:'Context Window',definition:'模型一次推理可納入考量的 Token 範圍上限。',note:'包含輸入、對話脈絡與部分系統資訊。'},
  {id:'gen04',category:'生成式 AI / NLP',term:'Prompt Engineering',definition:'設計與調整提示內容，以提升模型輸出品質與可控性的技巧。',note:'包含角色、限制、範例與輸出格式。'},
  {id:'gen05',category:'生成式 AI / NLP',term:'Zero-shot',definition:'未提供任務範例，直接要求模型完成任務。',note:'依賴模型既有知識與指令理解能力。'},
  {id:'gen06',category:'生成式 AI / NLP',term:'Few-shot',definition:'在提示中提供少量範例，引導模型學習目標輸出方式。',note:'屬於 in-context learning 的常見方式。'},
  {id:'gen07',category:'生成式 AI / NLP',term:'Hallucination',definition:'模型生成看似合理但實際錯誤、虛構或無法被來源支持的內容。',note:'需透過檢索、驗證或約束降低風險。'},
  {id:'gen08',category:'生成式 AI / NLP',term:'RAG',definition:'在生成前先檢索外部知識，再將檢索結果提供給模型作答。',note:'Retrieval-Augmented Generation。'},
  {id:'gen09',category:'生成式 AI / NLP',term:'Embedding',definition:'把文字、圖片等資料轉換為可比較語意關係的向量表示。',note:'常用於語意搜尋與向量資料庫。'},
  {id:'gen10',category:'生成式 AI / NLP',term:'Vector Database',definition:'專門儲存與搜尋向量嵌入，支援相似度查詢的資料庫。',note:'常與 RAG 搭配。'},
  {id:'gen11',category:'生成式 AI / NLP',term:'Chunking',definition:'把長文件切成較小片段，方便嵌入、檢索與模型處理。',note:'切分大小與重疊策略會影響 RAG 效果。'},
  {id:'gen12',category:'生成式 AI / NLP',term:'Semantic Search',definition:'依內容語意相似度，而非只靠關鍵字完全一致來搜尋。',note:'通常以 Embedding 向量計算相似度。'},
  {id:'gen13',category:'生成式 AI / NLP',term:'RLHF',definition:'利用人類偏好回饋來調整模型行為的強化學習方法。',note:'Reinforcement Learning from Human Feedback。'},
  {id:'gen14',category:'生成式 AI / NLP',term:'Function Calling',definition:'讓模型依結構化參數選擇並呼叫外部函式或工具。',note:'模型負責決定工具與參數，實際執行由外部系統完成。'},
  {id:'gen15',category:'生成式 AI / NLP',term:'AI Agent',definition:'能根據目標與情境進行推理、選擇工具並執行多步任務的 AI 系統。',note:'常包含規劃、工具調用、記憶與回饋迴圈。'},
  {id:'data01',category:'資料工程 / 大數據',term:'ETL',definition:'先擷取資料、再轉換，最後載入目標系統。',note:'Extract、Transform、Load。'},
  {id:'data02',category:'資料工程 / 大數據',term:'ELT',definition:'先擷取並載入資料，再於目標平台中進行轉換。',note:'常見於雲端資料倉儲架構。'},
  {id:'data03',category:'資料工程 / 大數據',term:'Data Lake',definition:'大量保存原始或不同格式資料的集中式儲存環境。',note:'可容納結構化、半結構化與非結構化資料。'},
  {id:'data04',category:'資料工程 / 大數據',term:'Data Warehouse',definition:'經整理整合後，主要支援分析與報表的資料儲存系統。',note:'通常有較明確的 Schema 與資料品質要求。'},
  {id:'data05',category:'資料工程 / 大數據',term:'Data Mart',definition:'針對特定部門或主題建立的較小型分析資料集合。',note:'例如財務或銷售專用資料市集。'},
  {id:'data06',category:'資料工程 / 大數據',term:'Pipeline',definition:'將多個資料處理步驟串接成可重複執行的流程。',note:'可涵蓋擷取、清理、轉換、模型推論等。'},
  {id:'data07',category:'資料工程 / 大數據',term:'Batch Processing',definition:'累積一批資料後，在特定時間一次處理。',note:'適合非即時、可排程的工作。'},
  {id:'data08',category:'資料工程 / 大數據',term:'Stream Processing',definition:'資料持續進入時即時或近即時地處理。',note:'適合事件流、感測資料與即時監控。'},
  {id:'data09',category:'資料工程 / 大數據',term:'Structured Data',definition:'具有固定欄位與明確結構的資料。',note:'例如關聯式資料表。'},
  {id:'data10',category:'資料工程 / 大數據',term:'Semi-structured Data',definition:'沒有固定表格結構，但仍包含標籤或階層資訊的資料。',note:'例如 JSON、XML。'},
  {id:'data11',category:'資料工程 / 大數據',term:'Unstructured Data',definition:'沒有預先定義固定資料模型的內容。',note:'例如自由文字、圖片、音訊、影片。'},
  {id:'data12',category:'資料工程 / 大數據',term:'Data Cleaning',definition:'修正缺失、重複、錯誤與不一致資料的處理過程。',note:'是資料前處理的重要步驟。'},
  {id:'data13',category:'資料工程 / 大數據',term:'Data Governance',definition:'管理資料品質、權責、安全、可用性與生命週期的制度與流程。',note:'不只是技術，也包含政策與責任。'},
  {id:'data14',category:'資料工程 / 大數據',term:'Metadata',definition:'描述資料本身的資料，例如欄位名稱、來源、格式與更新時間。',note:'可協助治理、搜尋與血緣追蹤。'},
  {id:'data15',category:'資料工程 / 大數據',term:'Schema',definition:'定義資料欄位、型別與結構規則的設計。',note:'關聯式資料庫通常有明確 Schema。'},
  {id:'api01',category:'API / 微服務',term:'API',definition:'讓不同軟體系統依規格交換資料或呼叫功能的介面。',note:'Application Programming Interface。'},
  {id:'api02',category:'API / 微服務',term:'RESTful',definition:'以資源與 HTTP 方法為核心設計 Web API 的架構風格。',note:'常搭配 GET、POST、PUT、DELETE。'},
  {id:'api03',category:'API / 微服務',term:'GraphQL',definition:'讓用戶端自行指定需要哪些欄位的 API 查詢語言與規格。',note:'可降低過度取得或取得不足的資料問題。'},
  {id:'api04',category:'API / 微服務',term:'FastAPI',definition:'以 Python 建立 Web API 的高效能框架。',note:'常見特色包括型別提示與自動 API 文件。'},
  {id:'api05',category:'API / 微服務',term:'Flask',definition:'輕量級 Python Web Framework，可用來建立網站與 API。',note:'彈性高、核心簡潔。'},
  {id:'api06',category:'API / 微服務',term:'Endpoint',definition:'API 對外提供特定資源或功能的存取位址。',note:'通常對應 URL 路徑與 HTTP 方法。'},
  {id:'api07',category:'API / 微服務',term:'JSON',definition:'常用於系統間交換結構化資料的文字格式。',note:'由鍵值、陣列等結構組成。'},
  {id:'api08',category:'API / 微服務',term:'Authentication',definition:'確認使用者或系統身分是否合法。',note:'回答「你是誰？」。'},
  {id:'api09',category:'API / 微服務',term:'Authorization',definition:'判斷已驗證身分是否有權執行特定操作。',note:'回答「你可以做什麼？」。'},
  {id:'api10',category:'API / 微服務',term:'API Key',definition:'用於識別與授權 API 呼叫者的憑證字串。',note:'不應硬編碼進公開程式碼。'},
  {id:'api11',category:'API / 微服務',term:'Microservices',definition:'把大型系統拆成多個可獨立部署與維護的小型服務。',note:'服務間通常透過 API 或訊息機制溝通。'},
  {id:'api12',category:'API / 微服務',term:'Service Discovery',definition:'讓微服務動態找到其他服務實例位置的機制。',note:'Consul、Eureka 常與此概念一起出現。'},
  {id:'api13',category:'API / 微服務',term:'Consul',definition:'可提供服務註冊、服務發現與健康檢查等功能的工具。',note:'屬於 HashiCorp 生態。'},
  {id:'api14',category:'API / 微服務',term:'Eureka',definition:'Netflix 開源的服務註冊與發現元件，常見於 Java 微服務生態。',note:'服務可註冊自己並查找其他服務。'},
  {id:'api15',category:'API / 微服務',term:'Hystrix',definition:'Netflix 曾推出的熔斷函式庫，用於避免下游服務故障造成連鎖失效。',note:'核心概念是 Circuit Breaker。'},
  {id:'ops01',category:'MLOps / 部署監控',term:'Docker',definition:'將應用程式與依賴封裝成可移植容器的技術與工具。',note:'有助於環境一致與部署。'},
  {id:'ops02',category:'MLOps / 部署監控',term:'Container',definition:'以隔離方式執行應用程式及其依賴的輕量化環境。',note:'相較 VM 通常更輕量。'},
  {id:'ops03',category:'MLOps / 部署監控',term:'Kubernetes',definition:'自動部署、擴縮與管理容器化應用的容器編排平台。',note:'常縮寫 K8s。'},
  {id:'ops04',category:'MLOps / 部署監控',term:'Pod',definition:'Kubernetes 中可部署的最小執行單位，可包含一個或多個容器。',note:'同一 Pod 中的容器共享部分網路與儲存資源。'},
  {id:'ops05',category:'MLOps / 部署監控',term:'CI/CD',definition:'透過自動化建置、測試與部署縮短軟體交付流程。',note:'Continuous Integration / Continuous Delivery or Deployment。'},
  {id:'ops06',category:'MLOps / 部署監控',term:'Canary Release',definition:'先將新版本釋出給少部分流量或使用者，再逐步擴大。',note:'可降低一次全面上線的風險。'},
  {id:'ops07',category:'MLOps / 部署監控',term:'Blue-Green Deployment',definition:'同時維持舊版與新版兩套環境，切換流量完成發布。',note:'有利於快速回滾。'},
  {id:'ops08',category:'MLOps / 部署監控',term:'Rollback',definition:'當新版本出現問題時，將系統退回先前穩定版本。',note:'是部署風險控制的重要能力。'},
  {id:'ops09',category:'MLOps / 部署監控',term:'Model Registry',definition:'集中管理模型版本、狀態與相關中繼資料的系統。',note:'支援模型生命週期與版本追蹤。'},
  {id:'ops10',category:'MLOps / 部署監控',term:'Model Serving',definition:'把訓練好的模型部署成可被其他系統呼叫的推論服務。',note:'常透過 API 提供預測。'},
  {id:'ops11',category:'MLOps / 部署監控',term:'Prometheus',definition:'收集與查詢時間序列 Metrics 的監控系統。',note:'常監控 CPU、Memory、Request Rate 等指標。'},
  {id:'ops12',category:'MLOps / 部署監控',term:'Alertmanager',definition:'接收監控告警並進行分組、抑制與通知路由的元件。',note:'常與 Prometheus 搭配。'},
  {id:'ops13',category:'MLOps / 部署監控',term:'Grafana',definition:'將監控與時間序列資料製作成 Dashboard 的視覺化平台。',note:'常與 Prometheus 搭配使用。'},
  {id:'ops14',category:'MLOps / 部署監控',term:'Data Drift',definition:'模型上線後，輸入資料的統計分布相較訓練期發生變化。',note:'可用 PSI、KS 等方法偵測。'},
  {id:'ops15',category:'MLOps / 部署監控',term:'Concept Drift',definition:'輸入特徵與目標結果之間的真實關係隨時間改變。',note:'即使輸入分布不明顯變化，模型仍可能失效。'},
  {id:'cloud01',category:'雲端 / 基礎架構',term:'IaaS',definition:'提供運算、網路與儲存等基礎資源，由使用者管理作業系統與應用。',note:'Infrastructure as a Service。'},
  {id:'cloud02',category:'雲端 / 基礎架構',term:'PaaS',definition:'提供應用程式執行與部署平台，減少自行管理底層基礎設施。',note:'Platform as a Service。'},
  {id:'cloud03',category:'雲端 / 基礎架構',term:'SaaS',definition:'使用者直接透過網路使用完整軟體服務。',note:'Software as a Service。'},
  {id:'cloud04',category:'雲端 / 基礎架構',term:'Virtual Machine',definition:'以虛擬化技術模擬完整電腦環境，通常包含自己的作業系統。',note:'常縮寫 VM。'},
  {id:'cloud05',category:'雲端 / 基礎架構',term:'OpenStack',definition:'用於建立與管理私有或公有雲基礎設施的開源平台。',note:'可管理運算、網路與儲存資源。'},
  {id:'cloud06',category:'雲端 / 基礎架構',term:'VMware',definition:'提供虛擬化與雲端基礎架構相關產品與平台的廠商及技術生態。',note:'常見於企業虛擬機環境。'},
  {id:'cloud07',category:'雲端 / 基礎架構',term:'CPU',definition:'通用型中央處理器，負責多種邏輯與運算工作。',note:'Central Processing Unit。'},
  {id:'cloud08',category:'雲端 / 基礎架構',term:'GPU',definition:'擅長大量平行運算的處理器，常用於深度學習訓練與推論。',note:'Graphics Processing Unit。'},
  {id:'cloud09',category:'雲端 / 基礎架構',term:'VRAM',definition:'顯示卡專用記憶體，會限制可載入的模型大小與影像生成工作量。',note:'本機 AI 推論常受 VRAM 容量限制。'},
  {id:'cloud10',category:'雲端 / 基礎架構',term:'Latency',definition:'從送出請求到獲得回應所需的延遲時間。',note:'即時應用通常希望越低越好。'},
  {id:'cloud11',category:'雲端 / 基礎架構',term:'Throughput',definition:'單位時間內系統可以處理的工作量或請求數。',note:'與 Latency 是不同面向的效能指標。'},
  {id:'cloud12',category:'雲端 / 基礎架構',term:'Uptime',definition:'服務維持可用狀態的時間比例。',note:'常用來衡量服務可用性。'},
  {id:'cloud13',category:'雲端 / 基礎架構',term:'Scalability',definition:'系統面對工作量增加時擴充資源並維持服務能力的特性。',note:'可包含水平與垂直擴充。'},
  {id:'cloud14',category:'雲端 / 基礎架構',term:'Horizontal Scaling',definition:'透過增加更多機器或服務實例來提升處理能力。',note:'也稱 Scale Out。'},
  {id:'cloud15',category:'雲端 / 基礎架構',term:'Vertical Scaling',definition:'提升單一機器的 CPU、RAM 等資源來增加處理能力。',note:'也稱 Scale Up。'},
  {id:'gov01',category:'AI 治理 / 專案管理',term:'Responsible AI',definition:'在公平、安全、透明、可問責等原則下設計與使用 AI。',note:'涵蓋技術與治理流程。'},
  {id:'gov02',category:'AI 治理 / 專案管理',term:'Explainability',definition:'能說明模型為何產生某個輸出或決策的程度。',note:'高風險情境通常更重視可解釋性。'},
  {id:'gov03',category:'AI 治理 / 專案管理',term:'Fairness',definition:'降低模型對不同群體產生不合理差別待遇的治理目標。',note:'需搭配偏見檢測與資料治理。'},
  {id:'gov04',category:'AI 治理 / 專案管理',term:'WEAT',definition:'用詞向量中的關聯強度檢測潛在社會偏見的方法。',note:'Word Embedding Association Test。'},
  {id:'gov05',category:'AI 治理 / 專案管理',term:'Robustness',definition:'模型面對雜訊、資料變動或干擾時仍維持合理表現的能力。',note:'中文常稱魯棒性或穩健性。'},
  {id:'gov06',category:'AI 治理 / 專案管理',term:'Transparency',definition:'讓利害關係人了解 AI 系統的用途、限制、資料與運作方式。',note:'透明不等同於公開全部程式碼。'},
  {id:'gov07',category:'AI 治理 / 專案管理',term:'Accountability',definition:'建立明確責任歸屬，使 AI 決策與影響有人負責。',note:'治理制度需定義決策者與執行者責任。'},
  {id:'gov08',category:'AI 治理 / 專案管理',term:'RACI',definition:'用 Responsible、Accountable、Consulted、Informed 劃分角色責任的矩陣。',note:'常用於專案治理與權責分工。'},
  {id:'gov09',category:'AI 治理 / 專案管理',term:'Responsible',definition:'在 RACI 中實際執行工作、把事情做完的角色。',note:'一項工作可有多個 Responsible。'},
  {id:'gov10',category:'AI 治理 / 專案管理',term:'Accountable',definition:'在 RACI 中對結果負最終責任並核准的角色。',note:'通常每項工作應有明確最終負責者。'},
  {id:'gov11',category:'AI 治理 / 專案管理',term:'Consulted',definition:'在 RACI 中執行前需要被徵詢意見的角色。',note:'屬於雙向溝通。'},
  {id:'gov12',category:'AI 治理 / 專案管理',term:'Informed',definition:'在 RACI 中需要被告知進度或結果的角色。',note:'通常以單向通知為主。'},
  {id:'gov13',category:'AI 治理 / 專案管理',term:'KPI',definition:'用來衡量系統、應用或業務成果是否達標的關鍵績效指標。',note:'AI 專案可分系統層、應用層與業務層 KPI。'},
  {id:'gov14',category:'AI 治理 / 專案管理',term:'ROI',definition:'衡量投入成本與產生效益之間報酬關係的指標。',note:'AI 專案常用來評估商業價值。'},
  {id:'gov15',category:'AI 治理 / 專案管理',term:'Model Card',definition:'記錄模型用途、限制、資料、評估與風險等資訊的模型文件。',note:'有助於透明度與模型治理。'}
];
