import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import worker,{validAnswer} from './server/worker.mjs';
import {assetHeaders} from './server/headers.mjs';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('server/schema.sql','utf8'));const wrap=(sql,args=[])=>({bind(...values){return wrap(sql,values)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const result=db.prepare(sql).run(...args);return {meta:{changes:result.changes}}}});return {db,env:{DB:{prepare:wrap,async batch(queries){db.exec('BEGIN');try{const r=await Promise.all(queries.map(q=>q.run()));db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}},JOIN_LIMIT:{limit:async()=>({success:true})},API_LIMIT:{limit:async()=>({success:true})}}}}
async function call(env,path,{token,method='GET',body}={}){return worker.fetch(new Request('https://game.test/api/'+path,{method,headers:{Origin:'https://game.test',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}),env)}
test('two independent identities, level separation, duplicate race and deletion isolation',async()=>{const {db,env}=fixture();const a=await (await call(env,'join',{method:'POST'})).json(),b=await (await call(env,'join',{method:'POST'})).json();assert.notEqual(a.token,b.token);const answer={level:'beginner',target:'b01',choice:'b01'};await Promise.all(Array.from({length:8},()=>call(env,'answer',{method:'POST',token:a.token,body:answer})));await call(env,'answer',{method:'POST',token:b.token,body:answer});await call(env,'answer',{method:'POST',token:b.token,body:{...answer,target:'b25',choice:'b25'}});const rank=await (await call(env,'ranking?level=beginner')).json();assert.deepEqual(rank.map(x=>x.stars),[2,1]);assert.equal((await (await call(env,'ranking?level=intermediate')).json()).length,0);assert.equal((await call(env,'me',{method:'DELETE'})).status,401);assert.equal((await call(env,'me',{method:'DELETE',token:a.token,body:{alias:b.alias}})).status,200);assert.equal((await (await call(env,'ranking?level=beginner')).json())[0].alias,b.alias);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM mastery').get().n,2);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM scores').get().n,1);assert.equal((await call(env,'answer',{method:'POST',token:a.token,body:answer})).status,401);db.close()});
test('malformed JSON, null, unknown levels and oversized streams are rejected',async()=>{const {db,env}=fixture();const a=await (await call(env,'join',{method:'POST'})).json();for(const body of ['{','null','[]','{}'])assert.equal((await call(env,'answer',{method:'POST',token:a.token,body})).status,400);assert.equal((await call(env,'answer',{method:'POST',token:a.token,body:'x'.repeat(1025)})).status,413);for(const level of ['__proto__','constructor','toString'])assert.equal(validAnswer(level,'x','x'),false);db.close()});
test('rate limits and database failure do not report success',async()=>{const {db,env}=fixture();env.API_LIMIT.limit=async()=>({success:false});assert.equal((await call(env,'join',{method:'POST'})).status,429);env.API_LIMIT.limit=async()=>({success:true});env.JOIN_LIMIT.limit=async()=>({success:false});assert.equal((await call(env,'join',{method:'POST'})).status,429);env.DB.prepare=()=>{throw Error('offline')};assert.equal((await call(env,'ranking?level=beginner')).status,503);db.close()});
test('schema is repeatable and summaries reconcile existing mastery',async()=>{const {db}=fixture();db.exec("INSERT INTO players VALUES('test','hash','alias');INSERT INTO mastery VALUES('test','beginner','b01')");db.exec(fs.readFileSync('server/schema.sql','utf8'));assert.equal(db.prepare('SELECT stars FROM scores').get().stars,1);db.exec("DELETE FROM players WHERE id='test'");assert.equal(db.prepare('SELECT COUNT(*) AS n FROM mastery').get().n,0);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM scores').get().n,0);db.close()});

test('static assets carry the security headers even if the platform ignores _headers',async()=>{const env={ASSETS:{fetch:async()=>new Response('<!doctype html>',{headers:{'Content-Type':'text/html'}})}};const r=await worker.fetch(new Request('https://game.test/index.html'),env);assert.equal(r.status,200);assert.equal(await r.text(),'<!doctype html>');for(const name of Object.keys(assetHeaders))assert.equal(r.headers.get(name),assetHeaders[name]);assert.ok(assetHeaders['Content-Security-Policy'].includes("frame-ancestors 'none'"))});
