window.TERM_ZH = {
  'Supervised Learning':'監督式學習','Unsupervised Learning':'非監督式學習','Reinforcement Learning':'強化學習','Transfer Learning':'遷移學習','Fine-tuning':'微調','Overfitting':'過度擬合','Underfitting':'欠擬合','Regularization':'正則化','Feature Engineering':'特徵工程','Feature Selection':'特徵選擇','PCA':'主成分分析','t-SNE':'t 分布隨機鄰近嵌入','Autoencoder':'自編碼器','K-means':'K 平均分群','KNN':'K 最近鄰',
  'Accuracy':'準確率','Precision':'精確率','Recall':'召回率','F1-score':'F1 分數','Confusion Matrix':'混淆矩陣','ROC Curve':'ROC 曲線','AUC':'曲線下面積','MAE':'平均絕對誤差','MSE':'均方誤差','RMSE':'均方根誤差','Pearson Correlation':'皮爾遜相關係數','Chi-square Test':'卡方檢定','Z-score':'Z 分數／標準分數','KS Statistic':'KS 統計量','PSI':'母體穩定性指標',
  'LLM':'大型語言模型','Token':'語元／權杖','Context Window':'上下文視窗','Prompt Engineering':'提示工程','Zero-shot':'零樣本學習／零樣本提示','Few-shot':'少樣本學習／少樣本提示','Hallucination':'幻覺','RAG':'檢索增強生成','Embedding':'嵌入向量','Vector Database':'向量資料庫','Chunking':'分塊／切塊','Semantic Search':'語意搜尋','RLHF':'人類回饋強化學習','Function Calling':'函式呼叫','AI Agent':'AI 代理人／智慧代理',
  'ETL':'擷取、轉換、載入','ELT':'擷取、載入、轉換','Data Lake':'資料湖','Data Warehouse':'資料倉儲','Data Mart':'資料市集','Data Pipeline':'資料管線','Batch Processing':'批次處理','Stream Processing':'串流處理','Structured Data':'結構化資料','Unstructured Data':'非結構化資料','Semi-structured Data':'半結構化資料','Data Cleaning':'資料清理','Data Transformation':'資料轉換','Data Integration':'資料整合','Data Governance':'資料治理',
  'API':'應用程式介面','RESTful':'REST 風格 API','GraphQL':'圖形查詢語言','FastAPI':'FastAPI Python API 框架','Flask':'Flask Python Web 框架','Endpoint':'端點','JSON':'JavaScript 物件表示法','HTTP':'超文字傳輸協定','GET':'取得資源','POST':'建立／提交資源','PUT':'更新／替換資源','DELETE':'刪除資源','Authentication':'身分驗證','Authorization':'授權','Microservices':'微服務',
  'Docker':'容器化平台','Container':'容器','Image':'映像檔','Kubernetes':'容器編排平台','Pod':'Pod 執行單位','Deployment':'部署物件','CI/CD':'持續整合／持續交付','Canary Release':'金絲雀發布','Blue-Green Deployment':'藍綠部署','Rollback':'回滾','Model Registry':'模型登錄庫','Model Serving':'模型服務化','Monitoring':'監控','Prometheus':'監控與指標收集系統','Alertmanager':'警報管理器',
  'Grafana':'監控視覺化平台','Evidently AI':'模型與資料漂移監控工具','Alibi Detect':'漂移與異常偵測工具','Data Drift':'資料漂移','Concept Drift':'概念漂移','Model Drift':'模型漂移','IaaS':'基礎設施即服務','PaaS':'平台即服務','SaaS':'軟體即服務','VM':'虛擬機器','VMware':'虛擬化平台','OpenStack':'開源雲端運算平台','CPU':'中央處理器','GPU':'圖形處理器','VRAM':'顯示記憶體',
  'Latency':'延遲','Throughput':'吞吐量','Uptime':'可用時間','Scalability':'可擴展性','High Availability':'高可用性','Fault Tolerance':'容錯能力','Load Balancing':'負載平衡','Horizontal Scaling':'水平擴展','Vertical Scaling':'垂直擴展','Responsible AI':'負責任 AI','Explainability':'可解釋性','Interpretability':'可理解性','Fairness':'公平性','Bias':'偏誤','WEAT':'詞嵌入關聯測試','Privacy':'隱私','Security':'安全性','Robustness':'魯棒性／穩健性','Accountability':'課責性','Transparency':'透明性','RACI':'責任分工矩陣','Responsible':'執行負責','Accountable':'最終負責','Consulted':'被諮詢','Informed':'被告知'
};