(() => {
let level=localStorage.getItem('ipasLevel')==='intermediate'?'intermediate':'beginner';
const $=id=>document.getElementById(id);let rankRequest=0;
const readStats=()=>{try{return JSON.parse(localStorage.getItem('ipasPlayStats:'+level)||'{}')}catch{return {}}};
async function ranking(){const request=++rankRequest;$('rankStatus').textContent='讀取世界榜…';$('ranking').replaceChildren();try{const data=await Community.rank(level);if(request!==rankRequest)return;$('rankStatus').textContent=data.length?'每個知識點計 1 星；最多顯示 50 位。':'還沒有紀錄，歡迎成為第一位探險家！';for(const r of data){const li=document.createElement('li');li.textContent=r.alias+' · '+r.stars+' ★';$('ranking').append(li)}}catch(e){if(request===rankRequest)$('rankStatus').textContent=e.message}}
function render(){localStorage.setItem('ipasLevel',level);document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.level===level)));document.querySelectorAll('[data-game]').forEach(a=>a.href='play.html?level='+level+'&game='+a.dataset.game);$('pythonIsland').hidden=level!=='intermediate';$('levelDescription').textContent=level==='beginner'?'初級航線：AI 基礎、資料處理、生成式 AI、導入與風險。':'中級航線：技術應用、大數據、機器學習與 Python 實作延伸。';const s=readStats();$('localStats').textContent=`累積作答 ${s.totalAnswered||0} 次 · 待複習 ${(s.wrongIds||[]).length} 題`;$('reviewLink').href='play.html?level='+level+'&review=1&game=truck';$('passport').textContent=Community.read()?.alias||'自由探險家';ranking()}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;render()});$('refresh').onclick=ranking;$('join').onclick=async()=>{try{const i=await Community.join();$('passport').textContent=i.alias;$('rankStatus').textContent='已加入！接下來答對的新知識點會同步。'}catch(e){$('rankStatus').textContent=e.message}};
$('deleteCloud').onclick=async()=>{if(!confirm('刪除你的世界榜身分與雲端知識點？本機練習紀錄仍保留。'))return;try{await Community.remove();render()}catch(e){$('rankStatus').textContent=e.message}};$('deleteLocal').onclick=()=>{if(!confirm('清除此裝置的學習紀錄？'))return;['ipasPlayStats','ipasPlayStats:beginner','ipasPlayStats:intermediate','ipasPythonStats'].forEach(k=>localStorage.removeItem(k));render()};
function motion(){const reduced=localStorage.getItem('ipasMotion')==='off'||matchMedia('(prefers-reduced-motion: reduce)').matches;document.body.classList.toggle('reduce',reduced);$('motion').textContent='動畫：'+(reduced?'關':'開')}$('motion').onclick=()=>{localStorage.setItem('ipasMotion',localStorage.getItem('ipasMotion')==='off'?'on':'off');motion()};motion();render();
})();
