import { answers } from './answers.mjs';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const digest=async token=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(x=>x.toString(16).padStart(2,'0')).join('');
export function validAnswer(level,target,choice){return typeof target==='string'&&typeof choice==='string'&&answers[level]?.[target]===choice}
export default {async fetch(req,env){const url=new URL(req.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(req);if(!env.DB)return json({error:'World ranking not configured'},503);if(req.headers.get('Origin')&&req.headers.get('Origin')!==url.origin)return json({error:'Origin not allowed'},403);try{
 if(req.method==='GET'&&url.pathname==='/api/ranking'){const level=url.searchParams.get('level');if(!['beginner','intermediate'].includes(level))return json({error:'Invalid level'},400);const {results}=await env.DB.prepare('SELECT p.alias, COUNT(*) AS stars FROM mastery m JOIN players p ON p.id=m.player_id WHERE m.level=? GROUP BY m.player_id ORDER BY stars DESC,p.alias ASC LIMIT 50').bind(level).all();return json(results)}
 if(req.method==='POST'&&url.pathname==='/api/join'){const token=crypto.randomUUID()+crypto.randomUUID(),id=crypto.randomUUID();const alias='探險家-'+id.slice(0,8);await env.DB.prepare('INSERT INTO players(id,token_hash,alias) VALUES(?,?,?)').bind(id,await digest(token),alias).run();return json({token,alias},201)}
 const auth=req.headers.get('Authorization')||'';if(!/^Bearer [a-f0-9-]{72}$/.test(auth))return json({error:'Unauthorized'},401);const player=await env.DB.prepare('SELECT id FROM players WHERE token_hash=?').bind(await digest(auth.slice(7))).first();if(!player)return json({error:'Unauthorized'},401);
 if(req.method==='DELETE'&&url.pathname==='/api/me'){await env.DB.batch([env.DB.prepare('DELETE FROM mastery WHERE player_id=?').bind(player.id),env.DB.prepare('DELETE FROM players WHERE id=?').bind(player.id)]);return json({deleted:true})}
 if(req.method==='POST'&&url.pathname==='/api/answer'){const body=await req.text();if(body.length>1024)return json({error:'Too large'},413);let v;try{v=JSON.parse(body)}catch{return json({error:'Invalid JSON'},400)}if(!validAnswer(v.level,v.target,v.choice))return json({error:'Invalid answer'},400);await env.DB.prepare('INSERT OR IGNORE INTO mastery(player_id,level,term_id) VALUES(?,?,?)').bind(player.id,v.level,v.target).run();return json({saved:true})}
 return json({error:'Not found'},404);
 }catch{return json({error:'Temporarily unavailable'},503)}}};
